version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-admintrativo
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: admintrativo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./data-mysql:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-admintrativo
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: password123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped
